### ISSUE TITLE
Ch_301 - Game players won't be able to ` redeemRewardsGame()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#187]
Ch_301

high

# Game players won't be able to ` redeemRewardsGame()`

## Summary
The modifier [onlyWhenVaultIsOn()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L75-L79) will revert in case the vault is off.

## Vulnerability Detail
The vault X is in the same chain/L with `game.sol`
In the case of vault X having `zero` allocations or having only 1 protocol on it which gets blacklisted over time.

Now, vault X is off and the Game players won't be able to [redeemRewards()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L545-L553) ==> [redeemRewardsGame()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L194-L204)
## Impact
The Game players won't be able to redeem rewards
The baskets will be updated with the wrong value

## Tool used

Manual Review

## Recommendation
```diff
  function redeemRewardsGame(
    uint256 _value,
    address _user
- ) external onlyGame nonReentrant onlyWhenVaultIsOn {
+ ) external onlyGame nonReentrant onlyWhenIdle {
    UserInfo storage user = userInfo[_user];
    require(user.rewardAllowance == 0, allowanceError);

    user.rewardAllowance = _value;
    user.rewardRequestPeriod = rebalancingPeriod;
    totalWithdrawalRequests += _value;
  }
```
Duplicate of #318

**Comment by Ch-301** [comment]
Escalate for 10 USDC

I will try to simplify it more
- Let's say `game.sol` and `vault X` are on Optimism
- We know if any vault gets zero allocations from **Game players**. anyone could invoke `XChainController.sendFeedbackToVault()` to turned that vault OFF.
- Now `vault X` is OFF.
- If any  **Game players** invoke `game.redeemRewards()` to redeem funds from a basket, the `MainVault.redeemRewardsGame()` will keep reverting because `onlyWhenVaultIsOn` modifier
- So no one will be able to redeem his rewards 

In the worst case if the `vault X` has only 1 protocol on it which gets blacklisted over time (or multiple protocols and all of them get blacklisted). no one will be able to redeem his rewards forever so **Game players** will lose funds

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I will try to simplify it more
> - Let's say `game.sol` and `vault X` are on Optimism
> - We know if any vault gets zero allocations from **Game players**. anyone could invoke `XChainController.sendFeedbackToVault()` to turned that vault OFF.
> - Now `vault X` is OFF.
> - If any  **Game players** invoke `game.redeemRewards()` to redeem funds from a basket, the `MainVault.redeemRewardsGame()` will keep reverting because `onlyWhenVaultIsOn` modifier
> - So no one will be able to redeem his rewards 
> 
> In the worst case if the `vault X` has only 1 protocol on it which gets blacklisted over time (or multiple protocols and all of them get blacklisted). no one will be able to redeem his rewards forever so **Game players** will lose funds
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Duplicate of #318

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Duplicate of #318 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
