### ISSUE TITLE
wzrdk3lly - Users can game the withdrawal system to prevent losing LP token value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#71]
wzrdk3lly

high

# Users can game the withdrawal system to prevent losing LP token value

## Summary

A user can prevent being impacted from a decline in LP token value by submitting a withdrawal request even when there is enough funds in the vault and when they have no intention of withdrawing. When the LP token declines in value, the user can claim their LP tokens at the higher price.

## Vulnerability Detail

1. Alice has 10 LP tokens worth a total of 1000 USD
2. Alice wants to ensure she doesn't lose her 1000 USD worth of tokens in the event of a negative price swing
3. Alice decides to create a withdrawal request so she can claim her allowance of 1000 USD when the value of the the LP token declines
4. The value of 10 LP tokens decline to 500 USD after a few months
5. Alice claims her withdrawalAllowance for 1000 USD value while the value of LP tokens is 500 USD

This is ultimately an accounting error that benefits users and hurts the protocol.

## Impact

The Derby protocol would be incurring a loss due to users being able to cheat the system whenever there are negative price changes in the LP token. This would also inadvertently make negative price swings worse because the more users that catch on to this vulnerability, the more users will cash out their high allowances during negative price action.

## Code Snippet

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L149-L162

1. On line 155 a user can lock in the value of their withdrawal

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L166-L179

2. On line 178, the user initiates the claim for their locked value even when the actual value is much lower

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L184-L188

3. On line 188 the user is successfully sent their locked value

## Tool used

Manual Review

## Recommendation

Implement a require check to ensure that a user is not creating a withdrawal request when the vault does indeed have funds AND incorporate proper logic to account for price swings of LP tokens in the time span between a withdrawal request and allowance withdrawal.

**Comment by wzrdk3lly** [comment]
Escalate for 10 USDC

The sponsor disputed my finding stating, "This is why we take into account the withdrawalRequest during the calculation of the new exchangeRate". I would like to point out that I'm not debating that the protocol doesn't calculate a newExchange rate. The issue I'm raising is that the withdrawal allowance does not use the newExchangeRate when the withdrawal allowance is invoked. The value from the withdawalRequest is the same value used in the withdrawal allowance, despite the update made to the newExchangeRate. Thus, my original finding/claim holds that a user can successful game the withdrawal functionality.

The logic is as follows:

1. Attacker makes withdrawal request A with exchange rate X
2. New exchange rate Y is calculated over the duration of 90 days. The LP token has lost a significant worth of its value.
3. Attacker decides to invoke their withdrawal allowance A which used the exchange rate X INSTEAD of the new exchange rate Y.

The gaming can be performed by anyone since an attacker can make a withdrawal request even when the vault has enough balance to cover a normal withdrawal AND the new exchange rate is not applied to their original withdrawal request. It's a unique way an attacker can manipulate protocol logic in their favor.

Please let me know if the team has any feedback or questions. Thank you.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> The sponsor disputed my finding stating, "This is why we take into account the withdrawalRequest during the calculation of the new exchangeRate". I would like to point out that I'm not debating that the protocol doesn't calculate a newExchange rate. The issue I'm raising is that the withdrawal allowance does not use the newExchangeRate when the withdrawal allowance is invoked. The value from the withdawalRequest is the same value used in the withdrawal allowance, despite the update made to the newExchangeRate. Thus, my original finding/claim holds that a user can successful game the withdrawal functionality.
> 
> The logic is as follows:
> 
> 1. Attacker makes withdrawal request A with exchange rate X
> 2. New exchange rate Y is calculated over the duration of 90 days. The LP token has lost a significant worth of its value.
> 3. Attacker decides to invoke their withdrawal allowance A which used the exchange rate X INSTEAD of the new exchange rate Y.
> 
> The gaming can be performed by anyone since an attacker can make a withdrawal request even when the vault has enough balance to cover a normal withdrawal AND the new exchange rate is not applied to their original withdrawal request. It's a unique way an attacker can manipulate protocol logic in their favor.
> 
> Please let me know if the team has any feedback or questions. Thank you.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Theezr** [comment]
@wzrdk3lly 

When a user withdraws his request after 90 days. He is supposed to get the old exchangeRate of 90 days ago. Otherwise there is no use for the withdrawalRequest. He wants to get out at that moment, but there are no funds. So he gets the right to withdraw later with the old exchangeRate. He cannot cancel the request, therefore we cant see how an attacker can manipulate protocol logic in their favor.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid high/medium issue
Given that the withdrawRequest/withdrawals work as intended as pointed out by the sponsor, there is no issue in this case.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid high/medium issue
> Given that the withdrawRequest/withdrawals work as intended as pointed out by the sponsor, there is no issue in this case. 
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
